default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Administração
    viewport:     width=device-width; initial-scale=1; maximum-scale=1; user-scalable=no
    language:     pt_BR

  stylesheets:    [backend/reset, backend/ui_custom, backend/datatable, backend/main]
  javascripts:    [/backend.php/home/javascript/js, backend/plugins/jquery.min, backend/plugins/jquery-ui.min, backend/plugins/ui/jquery.collapsible.min, backend/notifications, util, record, backend/record, backend/main]

  has_layout:     on
  layout:         layout
