default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Administração
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     pt_BR

  stylesheets:    [backend/layout]

  javascripts:    [backend/main, /sf/prototype/js/prototype, backend/jquery-1.5.2.min.js, backend/hideshow, backend/jquery.tablesorter.min.js, backend/jquery.equalHeight.js, util, record, /backend.php/home/javascript/debug/<?php echo Util::isDebug(true) ?>/js, phpEquivalents]

  has_layout:     on
  layout:         layout
