default:
  is_secure: on
  credentials: iRankSite

confirmPresence:
  is_secure: off
  
uploadPhoto:
  is_secure: off
  
facebookResult:
  is_secure: off

share:
  is_secure: off

facebookResultImage:
  is_secure: off

getPhoto:
  is_secure: off
  
getiPhoneAppXml:
  is_secure: off
  
javascript:
  is_secure: off
  
getPhotoCommentList:
  is_secure: off