default:
  http_metas:
    content-type: text/html

  metas:
    title:                    iRank - Poker Ranking
    robots:                   index, follow
    description:              O primeiro site de gerenciamento de torneios e rankings pessoais de poker. Agenda, rankings, estatísticas, bankroll, casas de poker e muito mais.
    keywords:                 irank, rank, loja, virtual, poker, poquer, club, clube, casas, ranking, pessoal, classificação, torneio, holdem, amigos, camisetas, jogo, agenda, fotos, etapa, cobertura, estatisticas, onde jogar
    language:                 pt
    viewport:                 width=device-width; initial-scale=0.7; maximum-scale=1; user-scalable=yes
    google-site-verification: rVtMbz421RebCZ23zz8eg6Vap1n2yWEXxLn8jM295nM
    
  stylesheets:    [main, loading, leftMenu, reset]
  javascripts:    [phpEquivalents, util, form, /sf/prototype/js/prototype, record, <?php echo Util::isDebug(true)?'/debug.php':'' ?>/home/javascript/home, main]

  has_layout:     on
  layout:         layout
  culture:        pt_BR
