default:
  http_metas:
    content-type: text/html

  metas:
    title:           iRank - Poker Ranking
    robots:          index, follow
    description:     iRank - O primeiro site de gerenciamento de rankings pessoais de poker para você e seus amigos
    keywords:        irank, rank, poker, poquer, ranking, pessoal, classificação, torneio, holdem, amigos, histórico, jogo, agenda, fotos, etapa, cobertura
    language:        pt
    viewport:        width=device-width; initial-scale=0.7; maximum-scale=1; user-scalable=yes
    
  stylesheets:    [/sf/sf_default/css/screen.css]
  javascripts:    []

  has_layout:     on
  layout:         maintenance
  culture:        pt_BR
