default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Administração
    language:     pt

  stylesheets:    [backend/main, backend/form, backend/loading, backend/toolbar]
  javascripts:    [phpEquivalents, backend/main, backend/common, backend/form, backend/paginator, backend/toolbar, backend/mask, backend/hotKey, backend/record, backend/util, /sf/prototype/js/prototype]

  has_layout:     on
  layout:         layout