indexSuccess:

  stylesheets:    [backend/reset, backend/fullcalendar, backend/datatable, backend/ui_custom, backend/prettyPhoto, backend/elfinder]
  javascripts:    [/backend.php/home/javascript/js]
