all:
  is_secure: on
  credentials: iRankSite
  
uploadPhoto:
  is_secure: off
  
getAppUpdatedData:
  is_secure: off
  
exportBankrollBatch:
  is_secure: off
  
resumeChart:
  is_secure: off  

bankrollChart:
  is_secure: off