all:
  stylesheets:    [backend/eventLive]
  javascripts:    [mask, backend/eventLive, backend/paginator]

  
edit:
  stylesheets:    []
  javascripts:    [backend/tableReorder/header, backend/tableReorder/redips-drag-min, backend/tableReorder/script]
  
editSuccess:
  stylesheets:    []
  javascripts:    [backend/tableReorder/header, backend/tableReorder/redips-drag-min, backend/tableReorder/script]
