all:
  stylesheets:    [backend/eventLive]
  javascripts:    [mask, backend/plugins/uploader/plupload, backend/plugins/uploader/plupload.html5.js, backend/plugins/uploader/plupload.html4.js, backend/plugins/uploader/jquery.plupload.queue.js, backend/eventLive]

editSuccess:
  stylesheets:    [backend/tableReorder/style]
  javascripts:    [backend/tableReorder/header, backend/tableReorder/redips-drag-min, backend/tableReorder/script]
