all:
  stylesheets:    [form, table, tableReorder, timer, timerWizard]
  javascripts:    [timer, timerWizard, /sf/prototype/js/scriptaculous]

indexSuccess:
  javascripts:    [tableReorder/header, tableReorder/redips-drag-min, tableReorder/timer]
  
timerSuccess:
  
  metas:
    viewport:                     width=device-width; height=device-height; initial-scale=1, maximum-scale=1.0, user-scalable=1
    apple-mobile-web-app-capable: yes
    
  stylesheets:    [-*, timer]
  javascripts:    [-*, mask, timer, /sf/prototype/js/prototype, /sf/prototype/js/scriptaculous, phpEquivalents]
  layout:         clean