# default rules

#CLUB ROUTING START

club_vegas:
  url:    /vegas
  param:  { module: club, action: details, clubId: 334 }

club_abluc:
  url:    /abluc
  param:  { module: club, action: details, clubId: 340 }

club_vegas:
  url:    /vegas
  param:  { module: club, action: details, clubId: 345 }

#CLUB ROUTING END

homepage:
  url:   /
  param: { module: home, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*