default:
  http_metas:
    content-type: text/html

  metas:
    title:           iRank - Poker Ranking
    robots:          index, follow
    description:     iRank - O primeiro site de gerenciamento de rankings pessoais de poker para você e seus amigos
    keywords:        irank, rank, poker, poquer, ranking, pessoal, classificação, torneio, holdem, amigos, histórico, jogo
    language:        pt
    viewport:        width=device-width; initial-scale=0.7; maximum-scale=1; user-scalable=yes
    
    og|title:        iRank - Poker Ranking
    og|description:  iRank - O primeiro site de gerenciamento de rankings de poker para você e seus amigos
    og|image*2:      http://<?php echo $host=MyTools::getRequest()->getHost() ?>/images/iphone.png
    og|image*1:      http://<?php echo $host ?>/images/layout/chips.png
    og|image:        http://<?php echo $host ?>/images/facebookLogo.gif

  stylesheets:    [main, loading]
  javascripts:    [phpEquivalents, main, util, form, /sf/prototype/js/prototype, record, /index.php/home/javascript/debug/<?php echo Util::isDebug(true) ?>/js]

  has_layout:     on
  layout:         layout3.1
  culture:        pt_BR
