default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank
    robots:       index, follow
    description:  iRank - O primeiro site de gerenciamento de rankings de poker para você e seus amigos
    keywords:     poker, ranking, classificação, torneio, holdem, amigos
    language:     pt

  stylesheets:    [main, frontend/layout, frontend/form, button, loading, frontend/login]
  javascripts:    [phpEquivalents, /sf/prototype/js/prototype, button, frontend/form, util, frontend/login, frontend/record, mask, frontend/friendSearch]

  has_layout:     on
  layout:         layout