all:
  stylesheets:    [form, table, event, eventComment, eventPhoto, lightbox]
  javascripts:    [event, eventComment, eventPhoto, rankingPlace, ranking, mask, /sf/prototype/js/scriptaculous, lightbox, /index.php/event/javascript/js]