all:
  stylesheets:    [form, table, eventComment, eventPhoto, lightbox, tableReorder, event]
  javascripts:    [event, eventComment, eventPhoto, rankingPlace, ranking, mask, /sf/prototype/js/scriptaculous, lightbox, /index.php/event/javascript/js, tableReorder/header, tableReorder/redips-drag-min, tableReorder]