all:
  stylesheets:    [frontend/table, frontend/form, frontend/event, frontend/eventComment, frontend/eventPhoto]
  javascripts:    [frontend/event, frontend/eventComment, frontend/eventPhoto, frontend/rankingPlace]