indexSuccess:

  stylesheets:    [backend/reset, backend/fullcalendar, backend/datatable, backend/ui_custom, backend/prettyPhoto, backend/elfinder]
  javascripts:    [backend/plugins/calendar.min.js, backend/home]
