default:
  is_secure: on
  credentials: [iRankAdmin]

index:
  credentials: [[iRankAdmin, iRankClub]]

edit:
  credentials: [[iRankAdmin, iRankClub]]

save:
  credentials: [[iRankAdmin, iRankClub]]

getCalendar:
  credentials: [[iRankAdmin, iRankClub]]
  
uploadLogo:
  is_secure: off

uploadPhotos:
  is_secure: off