all:

  stylesheets:    []
  javascripts:    [mask, backend/plugins/uploader/plupload, backend/plugins/uploader/plupload.html5.js, backend/plugins/uploader/plupload.html4.js, backend/plugins/uploader/jquery.plupload.queue.js, backend/club]
