all:
  
  stylesheets:    [form, table, login]
  javascripts:    [passwordRecovery, login]
  
passwordRecoverySuccess:
  
  stylesheets:    [form, table, passwordRecovery]
  javascripts:    [passwordRecovery]