all:

  stylesheets:    [backend/cashTable]
  javascripts:    [/backend.php/cashTable/javascript/debug/<?php echo Util::isDebug(true) ?>/js, backend/people, backend/cashTable, backend/cashTablePeople]
