default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Poker Ranking
    language:     en
    viewport:     width=device-width; initial-scale=1; maximum-scale=1; user-scalable=no

  stylesheets:    [ios/main]
  javascripts:    []

  has_layout:     on
  layout:         layout
  culture:        pt_BR