default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Poker Ranking
    language:     en
    viewport:     width=device-width; initial-scale=0.5; maximum-scale=0.5; user-scalable=no

  stylesheets:    [button, mobile/main, mobile/menu, mobile/loading, mobile/form]
  javascripts:    [phpEquivalents, mobile/main, mobile/mobile, /sf/prototype/js/prototype, button, mobile/record, util, frontend/form, /mobile.php/home/javascript/js]

  has_layout:     on
  layout:         layout
  culture:        en_US