all:
  stylesheets:    [backend/photos, backend/eventLive]
  javascripts:    [mask, backend/plugins/uploader/plupload, backend/plugins/uploader/plupload.html5.js, backend/plugins/uploader/plupload.html4.js, backend/plugins/uploader/jquery.plupload.queue.js, backend/eventLive]

editSuccess:
  stylesheets:    [backend/tableReorder/style, backend/plugins/jquery.lightbox-0.5.css]
  javascripts:    [backend/tableReorder/header, backend/tableReorder/redips-drag-min, backend/tableReorder/script, backend/plugins/jquery.lightbox-0.5.js]
