all:
  stylesheets:    [backend/eventLive]
  javascripts:    [mask, backend/eventLive, backend/paginator]

editSuccess:
  stylesheets:    [backend/tableReorder/style]
  javascripts:    [backend/tableReorder/header, backend/tableReorder/redips-drag-min, backend/tableReorder/script]
