all:

  stylesheets:    [backend/plugins/jquery.lightbox-0.5.css, backend/photos]
  javascripts:    [mask, backend/plugins/uploader/plupload, backend/plugins/uploader/plupload.html5.js, backend/plugins/uploader/plupload.html4.js, backend/plugins/uploader/jquery.plupload.queue.js, backend/plugins/jquery.lightbox-0.5.js, backend/club, backend/form]
