all:

  metas:
    title:        iRank Store - Poker Ranking
  
  stylesheets:    [quickResume, table, store]
  javascripts:    [store]

cartSuccess:
  
  stylesheets:    []
  javascripts:    [mask]
  
paymentSuccess:
  
  stylesheets:    [-store, form, store]
  javascripts:    [form, mask]
  
orderDetailsSuccess:
  
  stylesheets:    [si]
  javascripts:    [si]
  
billetSuccess:
  
  stylesheets:    [-*, store]
  javascripts:    [-*]
  
  has_layout:     on
  layout:         clean