all:
  
  stylesheets:    [table, store]
  javascripts:    [store]
  
cartSuccess:
  
  stylesheets:    []
  javascripts:    [mask]
  
paymentSuccess:
  
  stylesheets:    [-store, form, store]
  javascripts:    [form, mask]