#define kFeeKey @"fee"
#define kBuyinKey @"buyin"
#define kAddonKey @"addon"
#define kRebuyKey @"rebuy"
#define kPrizeKey @"prize"
#define kScoreKey @"score"
#define kBalanceKey @"balance"

#define kBuyinsWord @"Buy-ins"
#define kFeeWord @"Entradas"
#define kRebuysWord @"Rebuys"
#define kAddonsWord @"Addons"
#define kPrizesWord @"Prêmios"
#define kScoreWord @"Pontos"
#define kBalanceWord @"SALDO"


#define kSelectKey      @"selection"
#define kDescriptKey    @"description"
#define kControllerKey  @"viewController"