rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
mobile:
    class: MobileFilter
language:
    class: LanguageFilter

cache:     ~
common:    ~
flash:     ~
execution: ~
