default:
  http_metas:
    content-type: text/html

  metas:
    title:           iRank - Poker Ranking
    robots:          index, follow
    description:     iRank - O primeiro site de gerenciamento de rankings pessoais de poker para você e seus amigos
    keywords:        irank, rank, poker, poquer, ranking, pessoal, classificação, torneio, holdem, amigos, historico, jogo, bankroll, agenda, onde, jogar
    language:        pt
    
    og|title:        iRank - Poker Ranking
    og|description:  iRank - O primeiro site de gerenciamento de rankings de poker para você e seus amigos
    og|image:        http://<?php echo $host ?>/images/mediaLogo.png

  stylesheets:    [frontend/layout, frontend/loading]
  javascripts:    [phpEquivalents, main, util, frontend/form, /sf/prototype/js/prototype, frontend/record, /index.php/home/javascript/js]

  has_layout:     on
  layout:         layout
  culture:        pt_BR
