all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:                pgsql://postgres:unidunite@localhost/irank
#      dsn:                pgsql://irank:ir4nkc0mbr2010@pgsql.irank.com.br/irank
      phptype:            pgsql
      port:               5432
      encoding:           utf8
      persistent:         true
  log:
    class:          sfPropelDatabase
    param:
      dsn:                pgsql://postgres:unidunite@localhost/irank_log
#      dsn:                pgsql://irank:ir4nkc0mbr2010@pgsql.irank.com.br/irank
      phptype:            pgsql
      port:               5432
      encoding:           utf8
      persistent:         true
