all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:                pgsql://postgres:unidunite@localhost/irank
      phptype:            pgsql
      port:               5432
      encoding:           utf8
      persistent:         false
  log:
    class:          sfPropelDatabase
    param:
      dsn:                pgsql://postgres:unidunite@localhost/irank_log
