all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          pgsql://irank:ir4nkc0mbr2010@pgsql.irank.com.br/irank
  log:
    class:          sfPropelDatabase
    param:
      dsn:          pgsql://irank1:ir4nkL0G2012@pgsql.irank.com.br/irank1
