<?php include_partial('home/component/commonBar', array('pathList'=>array('Minha conta'=>'myAccount/index', 'Notificações'=>'myAccount/index?tab=sms', 'Termo SMS'=>null))); ?>
<div class="moduleIntro">
	<h1>Termos de uso das notificações via SMS</h1>
</div>
<hr class="separator"/>
<div class="moduleIntro">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse condimentum tempus libero sit amet dignissim. Etiam lacinia fringilla placerat. Nunc malesuada aliquet orci, eu cursus dui venenatis semper. Maecenas laoreet scelerisque massa at feugiat. Aliquam at elit eu velit porttitor suscipit. Nulla blandit sem pretium arcu consequat gravida. Morbi nunc leo, faucibus ut ornare lobortis, auctor non lectus. Mauris et turpis dui, non dictum lectus. Duis sit amet nisi in nunc adipiscing ultricies convallis in tellus. Integer dignissim, ligula vitae consequat dapibus, lacus libero porttitor urna, at malesuada magna velit nec augue. Nam aliquam sapien eu turpis tempus in fringilla odio rhoncus. Aliquam erat volutpat. Maecenas fermentum dapibus velit vitae tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum leo sapien, dictum a imperdiet id, interdum ac felis.</p>

<p>Sed semper erat at magna lobortis eleifend. Sed non sagittis risus. Aliquam interdum, tellus at ultricies auctor, nisl purus ornare mauris, iaculis pulvinar turpis ante in odio. Curabitur eleifend pharetra massa, venenatis sodales velit suscipit sed. Aliquam eget augue massa, quis faucibus magna. In hac habitasse platea dictumst. Sed eget ipsum at diam scelerisque convallis. Phasellus ornare, nulla eget imperdiet posuere, lectus nulla iaculis neque, vitae ullamcorper tellus nisi eget tortor. Nunc justo dui, suscipit sit amet volutpat ac, suscipit sit amet mi. Donec quis augue neque.</p>

<p>Praesent eu dui quis libero lacinia iaculis a et purus. Duis et diam tortor. Praesent quis diam dolor. Sed rutrum diam in nulla convallis vulputate pretium arcu ullamcorper. Suspendisse potenti. Curabitur luctus consequat ante non gravida. Suspendisse egestas consequat tellus nec lobortis. Etiam ac velit quis nulla luctus vulputate.</p>

<p>Cras eget lacus ut nulla ornare suscipit. Nullam tincidunt eros quis diam ullamcorper molestie. Praesent erat lectus, malesuada quis posuere non, ultricies ut diam. Morbi enim quam, lacinia vitae dapibus eu, facilisis et mauris. Nulla eget tristique massa. Sed sit amet tellus nisi, vel tempus justo. Nunc non tincidunt libero. Pellentesque eleifend, magna interdum euismod laoreet, ligula urna gravida elit, quis tincidunt lacus massa ac nunc. Donec a urna vitae quam sollicitudin dictum non quis elit.</p>

<p>Nulla sed mi at elit tristique blandit auctor in ante. Phasellus a risus nulla, nec convallis metus. Etiam ac malesuada justo. Vestibulum quis urna nunc, vel porttitor nisl. Nunc vel lacus velit, ut euismod metus. Nunc imperdiet accumsan convallis. Morbi sed nisl risus, vitae ultricies eros. Praesent ligula neque, pharetra vitae lacinia pretium, imperdiet eget neque. Phasellus sit amet augue quam, id aliquam dolor. Sed porttitor, risus in tristique imperdiet, ligula metus pellentesque ipsum, ac congue sapien magna ut lorem. Vestibulum neque enim, euismod eu auctor quis, ullamcorper sit amet nisi. Cras quis urna eget massa eleifend blandit eu eget magna. Aenean accumsan ultricies dui, sed lobortis ante mollis ut.</p>

<p>Quisque ornare molestie mi, id lobortis turpis pharetra ac. Proin suscipit nunc et eros consectetur imperdiet. Nulla adipiscing commodo imperdiet. Etiam auctor imperdiet semper. Vivamus tellus arcu, eleifend quis blandit ut, hendrerit eu diam. Vivamus sit amet dictum dui. Duis diam lectus, pharetra quis condimentum ac, hendrerit id ipsum. Aenean consectetur, odio in vulputate rutrum, elit mi posuere mauris, quis feugiat lacus enim egestas lectus. Pellentesque eget fringilla mauris. Donec non leo ligula, a vulputate turpis. Pellentesque id nibh magna.</p>

<p>Sed aliquet turpis nec ante auctor fringilla. Nam pharetra semper suscipit. Mauris a tellus eget libero dignissim hendrerit. Nulla varius orci eu ligula malesuada fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In porta elit massa, et rutrum lacus. Cras laoreet convallis ullamcorper. Mauris urna leo, ultrices a convallis in, placerat quis justo.</p>

<p>Donec luctus luctus suscipit. Quisque sit amet sem odio, ut tincidunt lorem. Ut consequat, nisl a aliquet viverra, nunc metus dignissim turpis, et blandit massa tortor sed urna. Morbi nunc urna, fringilla eu aliquam eu, lacinia blandit purus. Nulla facilisi. Nullam rhoncus turpis lacinia nisi sollicitudin eu commodo metus rhoncus. Curabitur auctor suscipit nunc, quis molestie odio placerat rhoncus.</p>

<p>Nulla aliquet ultricies nibh et ultrices. Fusce pulvinar justo id nisi laoreet non feugiat neque egestas. Cras molestie enim ut mauris suscipit tincidunt. Cras nec sollicitudin justo. Morbi rutrum dui nec lacus faucibus id tincidunt erat tempus. Praesent pellentesque sagittis nibh, nec placerat est convallis quis. Vivamus ac dui vel risus sollicitudin scelerisque. Nam sit amet est non nunc consectetur interdum ut sed leo. Praesent posuere lacus a dui placerat interdum. Aenean aliquam leo id nibh vulputate non gravida massa tristique. Praesent et est et libero imperdiet accumsan.</p>

<p>Duis tortor lectus, viverra ac congue vitae, interdum id turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras id felis nisl, a ornare lacus. Nulla ipsum sapien, accumsan id ultricies eget, facilisis laoreet sem. Aliquam a aliquet metus. Quisque luctus dictum iaculis. Quisque vel felis nec augue scelerisque aliquam sit amet vel ipsum. Ut id velit magna.</p> 
</div>