# default rules


# REGRAS PARA O MÓDULO EVENTOS
event_details:
  url:    /eventLive/details/:eventCode
  param:  { module: eventLive, action: details }

event_share:
  url:    /event/share/:shareId
  param:  { module: event, action: share }

event_result_share:
  url:    /event/resultShare/:shareId
  param:  { module: event, action: facebookResultShare }
  
event_permalink:
  url:    /event/:rankingTag/:eventDate/:eventName
  param:  { module: event, action: permalink }
  requirements:
    rankingTag: "[a-zA-Z0-9]+[a-z0-9_]*"
    eventDate: "[0-9]{4}-[0-9]{2}-[0-9]{2}"
    
email_option:
  url:    /emailOption/:emailAddress/:emailToken
  param:  { module: emailOption, action: index }


# REGRAS PARA O MÓDULO LOJA VIRTUAL
store_details:
  url:    /store/details/:productCode
  param:  { module: store, action: details }

store_add_item:
  url:    /store/addItem/:productCode
  param:  { module: store, action: addItem }

store_order_confirm:
  url:    /store/orderConfirm/:orderNumber
  param:  { module: store, action: orderConfirm }

store_billet:
  url:    /store/billet/:orderNumber
  param:  { module: store, action: billet }


# REGRAS PARA EMAILS
email_log:
  url:   /home/:emailLogId/logo/:fileName
  param: { module: home, action: images }

  
# REGRAS PARA O BLOG

rss:
  url:    blog/rss
  param:  { module: blog, action: feed }
  
blog_by_title:
  url:    blog/:permalink
  param:  { module: blog, action: index }

blog_by_title_html:
  url:    blog/:permalink.html
  param:  { module: blog, action: article }

article_by_title:
  url:    blog/article/:permalink
  param:  { module: blog, action: article }
  
glossaryBlog:
  url:    blog/getDictionary/:term
  param:  { module: blog, action: getDictionary }
  
glossaryTerm:
  url:    glossary/term/:term
  param:  { module: glossary, action: term }
  
glossaryLetter:
  url:    glossary/letter/:letter
  param:  { module: glossary, action: letter }



  
  
  
  
  
  
  
  


#CLUB ROUTING START

club_vegas:
  url:    /vegas
  param:  { module: club, action: details, clubId: 4 }

club_h2club:
  url:    /h2club
  param:  { module: club, action: details, clubId: 3 }

club_espaco:
  url:    /zahle
  param:  { module: club, action: details, clubId: 2 }

club_blackriver:
  url:    /blackriver
  param:  { module: club, action: details, clubId: 1 }

club_72off:
  url:    /72off
  param:  { module: club, action: details, clubId: 6 }

club_ases:
  url:    /ases
  param:  { module: club, action: details, clubId: 7 }

club_sierrapoker:
  url:    /sierrapoker
  param:  { module: club, action: details, clubId: 9 }

club_royalclub:
  url:    /royalclub
  param:  { module: club, action: details, clubId: 10 }

club_nltexasclub:
  url:    /nltexasclub
  param:  { module: club, action: details, clubId: 11 }

club_bsb:
  url:    /bsb
  param:  { module: club, action: details, clubId: 12 }

club_lol:
  url:    /lol
  param:  { module: club, action: details, clubId: 13 }

club_cwb:
  url:    /cwb
  param:  { module: club, action: details, clubId: 15 }

club_allin:
  url:    /allin
  param:  { module: club, action: details, clubId: 16 }

club_riverclub:
  url:    /riverclub
  param:  { module: club, action: details, clubId: 17 }

club_cataratas:
  url:    /cataratas
  param:  { module: club, action: details, clubId: 18 }

club_nit:
  url:    /nit
  param:  { module: club, action: details, clubId: 19 }

club_rivertexas:
  url:    /rivertexas
  param:  { module: club, action: details, clubId: 20 }

club_blackriver:
  url:    /blackriver
  param:  { module: club, action: details, clubId: 1 }

club_fgp:
  url:    /fgp
  param:  { module: club, action: details, clubId: 22 }

club_prudentepoker:
  url:    /prudentepoker
  param:  { module: club, action: details, clubId: 23 }

club_maceioholdem:
  url:    /maceioholdem
  param:  { module: club, action: details, clubId: 24 }

club_hitz:
  url:    /hitz
  param:  { module: club, action: details, clubId: 25 }

#CLUB ROUTING END
  
  
  
  
  
  
homepage:
  url:   /
  param: { module: home, action: index }
#  param: { module: maintenance, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
#  url:   /maintenance
  param: { action: index }

default:
  url:   /:module/:action/*
#  url:   /maintenance/index/*
