# default rules


# REGRAS PARA O MÓDULO EVENTOS
event_details:
  url:    /eventLive/details/:eventCode
  param:  { module: eventLive, action: details }

event_share:
  url:    /share/:shareId
  param:  { module: event, action: facebookResult }


# REGRAS PARA O MÓDULO LOJA VIRTUAL
store_details:
  url:    /store/details/:productCode
  param:  { module: store, action: details }

store_add_item:
  url:    /store/addItem/:productCode
  param:  { module: store, action: addItem }

store_order_confirm:
  url:    /store/orderConfirm/:orderNumber
  param:  { module: store, action: orderConfirm }

store_billet:
  url:    /store/billet/:orderNumber
  param:  { module: store, action: billet }


# REGRAS PARA EMAILS
email_log:
  url:   /home/:emailLogId/logo/:fileName
  param: { module: home, action: images }

  
# REGRAS PARA O BLOG
blog_by_title:
  url:    blog/:permalink
  param:  { module: blog, action: article }

blog_by_title_html:
  url:    blog/:permalink.html
  param:  { module: blog, action: article }

article_by_title:
  url:    blog/article/:permalink
  param:  { module: blog, action: article }
  
  
  
  
  
  
homepage:
  url:   /
  param: { module: home, action: index }
#  param: { module: maintenance, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
#  url:   /maintenance
  param: { action: index }

default:
  url:   /:module/:action/*
#  url:   /maintenance/index/*

  
  
  
  
  
  
  
  


#CLUB ROUTING START

club_vegas:
  url:    /vegas
  param:  { module: club, action: details, clubId: 5 }

club_irank:
  url:    /irank
  param:  { module: club, action: details, clubId: 6 }

club_irank:
  url:    /irank
  param:  { module: club, action: details, clubId: 5 }

club_irank:
  url:    /irank
  param:  { module: club, action: details, clubId: 6 }

club_irank:
  url:    /irank
  param:  { module: club, action: details, clubId: 5 }

club_h2club:
  url:    /h2club
  param:  { module: club, action: details, clubId: 3 }

club_espaco:
  url:    /espaco
  param:  { module: club, action: details, clubId: 2 }

club_blackriver:
  url:    /blackriver
  param:  { module: club, action: details, clubId: 1 }

#CLUB ROUTING END
