# default rules


# REGRAS PARA O MÓDULO EVENTOS
event_details:
  url:    /eventLive/details/:eventCode
  param:  { module: eventLive, action: details }

event_share:
  url:    /event/share/:shareId
  param:  { module: event, action: share }

event_result_share:
  url:    /event/resultShare/:shareId
  param:  { module: event, action: facebookResultShare }
  
event_permalink:
  url:    /event/:rankingTag/:eventDate/:eventName
  param:  { module: event, action: permalink }
  requirements:
    rankingTag: "[a-zA-Z0-9]+[a-z0-9_]*"
    eventDate: "[0-9]{4}-[0-9]{2}-[0-9]{2}"
    
email_option:
  url:    /emailOption/:emailAddress/:emailToken
  param:  { module: emailOption, action: index }


# REGRAS PARA O MÓDULO LOJA VIRTUAL
store_details:
  url:    /store/details/:productCode
  param:  { module: store, action: details }

store_add_item:
  url:    /store/addItem/:productCode
  param:  { module: store, action: addItem }

store_order_confirm:
  url:    /store/orderConfirm/:orderNumber
  param:  { module: store, action: orderConfirm }

store_billet:
  url:    /store/billet/:orderNumber
  param:  { module: store, action: billet }


# REGRAS PARA EMAILS
email_log:
  url:   /home/:emailLogId/logo/:fileName
  param: { module: home, action: images }

  
# REGRAS PARA O BLOG

rss:
  url:    blog/rss
  param:  { module: blog, action: rss }
  
blog_by_title:
  url:    blog/:permalink
  param:  { module: blog, action: index }

blog_by_title_html:
  url:    blog/:permalink.html
  param:  { module: blog, action: article }

article_by_title:
  url:    blog/article/:permalink
  param:  { module: blog, action: article }
  
glossary:
  url:    blog/getDictionary/:term
  param:  { module: blog, action: getDictionary }



  
  
  
  
  
  
  
  


#CLUB ROUTING START

club_vegas:
  url:    /vegas
  param:  { module: club, action: details, clubId: 4 }

club_h2club:
  url:    /h2club
  param:  { module: club, action: details, clubId: 3 }

club_espaco:
  url:    /zahle
  param:  { module: club, action: details, clubId: 2 }

club_blackriver:
  url:    /blackriver
  param:  { module: club, action: details, clubId: 1 }

club_72off:
  url:    /72off
  param:  { module: club, action: details, clubId: 6 }

club_ases:
  url:    /ases
  param:  { module: club, action: details, clubId: 7 }

#CLUB ROUTING END
  
  
  
  
  
  
homepage:
  url:   /
  param: { module: home, action: index }
#  param: { module: maintenance, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
#  url:   /maintenance
  param: { action: index }

default:
  url:   /:module/:action/*
#  url:   /maintenance/index/*
