all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          pgsql://postgres:unidunite@localhost/irank
  log:
    class:          sfPropelDatabase
    param:
      dsn:          pgsql://postgres:unidunite@localhost/irank_log
