all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:                pgsql://irank:ir4nkc0mbr13@pgsql.irank.com.br/irank
      phptype:            pgsql
      port:               5432
      encoding:           utf8
      persistent:         true
  log:
    class:          sfPropelDatabase
    param:
      dsn:                pgsql://irank1:ir4nkc0mbr13@pgsql.irank.com.br/irank1
