all:
  
  metas:
    og|title:        iRank - Poker Ranking
    og|description:  iRank - O primeiro site de gerenciamento de rankings de poker para você e seus amigos
    
  stylesheets:    [highlight, quickResume, eventResume, eventLiveResume, home]
  javascripts:    [highlight, home]
  
indexSuccess:
  stylesheets:    [quickResume]
  javascripts:    [] 
  
error404Success:
  stylesheets:    [table]
  javascripts:    [] 
  