all:

  stylesheets:    [backend/plugins/elfinder/elfinder.min.css, backend/blog]
  javascripts:    [backend/plugins/forms/jquery.cleditor.js, backend/plugins/forms/jquery.tagsinput.min.js, backend/plugins/elfinder.min.js, backend/plugins/elfinder.pt_BR.js, backend/blog]
