default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank
    language:     pt

  stylesheets:    [main, frontend/layout, frontend/form, button, loading, frontend/login]
  javascripts:    [phpEquivalents, /sf/prototype/js/prototype, button, frontend/form, util, frontend/login, frontend/record, mask]

  has_layout:     on
  layout:         layout