default:
  http_metas:
    content-type: text/html

  metas:
    title:           iRank - Poker Ranking
    robots:          index, follow
    description:     iRank - O primeiro site de gerenciamento de rankings pessoais de poker para você e seus amigos
    keywords:        irank, rank, poker, poquer, ranking, pessoal, classificação, torneio, holdem, amigos, histórico, jogo
    language:        pt
    viewport:        width=device-width; initial-scale=0.7; maximum-scale=1; user-scalable=yes
    
  stylesheets:    [main, loading, leftMenu]
  javascripts:    [phpEquivalents, main, util, form, /sf/prototype/js/prototype, record, /index.php/home/javascript/debug/<?php echo Util::isDebug(true) ?>/js]

  has_layout:     on
  layout:         layout3.1
  culture:        pt_BR
