all:
  propel:
    class:          sfPropelDatabase
    param:
#      dsn:                pgsql://postgres:unidunite@localhost/irank
      dsn:                pgsql://irank1:ir4nk4lph4@pgsql.irank.com.br/irank1
      phptype:            pgsql
      port:               5432
      encoding:           utf8
      persistent:         true
  log:
    class:          sfPropelDatabase
    param:
      dsn:          pgsql://postgres:unidunite@localhost/irank_log
      phptype:            pgsql
      port:               5432
      encoding:           utf8
      persistent:         true