default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Poker Ranking
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [-*, backend/login/invalid, backend/login/reset, backend/login/style]

  javascripts:    [-*, -*, -*, -*, util, /sf/prototype/js/prototype, phpEquivalents, backend/login]

  has_layout:     on
  layout:         login