default:
  http_metas:
    content-type: text/html

  metas:
    title:        iRank - Poker Ranking
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [-*, backend/login]

  javascripts:    [-*, -*, -*, -*, -*, /sf/prototype/js/prototype, phpEquivalents]

  has_layout:     on
  layout:         login